#!/bin/sh

# merge all ntuples

idir=$1
odir=$2

merge.py -i $idir -o $odir -d VBF_HToZZTo4Nu_M120
merge.py -i $idir -o $odir -d VBF_HToZZTo4Nu_M150
merge.py -i $idir -o $odir -d VBF_HToZZTo4Nu_M200
merge.py -i $idir -o $odir -d VBF_HToZZTo4Nu_M300
merge.py -i $idir -o $odir -d VBF_HToZZTo4Nu_M400
merge.py -i $idir -o $odir -d QCD_Pt-30to50
merge.py -i $idir -o $odir -d QCD_Pt-50to80
merge.py -i $idir -o $odir -d QCD_Pt-80to120
merge.py -i $idir -o $odir -d QCD_Pt-120to170
merge.py -i $idir -o $odir -d QCD_Pt-170to300
merge.py -i $idir -o $odir -d QCD_Pt-300to470
merge.py -i $idir -o $odir -d QCD_Pt-470to600
merge.py -i $idir -o $odir -d QCD_Pt-600to800
merge.py -i $idir -o $odir -d QCD_Pt-800to1000
merge.py -i $idir -o $odir -d QCD_Pt-1000to1400
merge.py -i $idir -o $odir -d QCD_Pt-1400to1800
merge.py -i $idir -o $odir -d QCD_Pt-1800
merge.py -i $idir -o $odir -d WJetsToLNu
merge.py -i $idir -o $odir -d WJetsToLNu_250_HT_300
merge.py -i $idir -o $odir -d WJetsToLNu_300_HT_400
merge.py -i $idir -o $odir -d WJetsToLNu_400_HT_inf
merge.py -i $idir -o $odir -d ZJetsToNuNu_50_HT_100
merge.py -i $idir -o $odir -d ZJetsToNuNu_100_HT_200
merge.py -i $idir -o $odir -d ZJetsToNuNu_200_HT_400
merge.py -i $idir -o $odir -d ZJetsToNuNu_400_HT_inf
merge.py -i $idir -o $odir -d DYJetsToLL

